FROM python:3.9-slim

WORKDIR /app

COPY requirements/requirements_worker.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src/workerNode.py .
COPY src/connectService.py .
COPY src/lokiHandler.py .

EXPOSE 8001 8002 8003

ENV WORKER_PORT=8001

CMD ["python", "workerNode.py"]
