FROM python:3.9

# Tini 설치
RUN apt-get update && apt-get install -y tini && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements/requirements_producer.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src/workerProducer.py .
COPY src/connectService.py .

CMD ["python", "workerProducer.py"]
