FROM python:3.9-slim

WORKDIR /app

COPY requirements/requirements_producer.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src/workerProducer.py .
COPY src/connectService.py .

CMD ["python", "workerProducer.py"]
