global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'worker1'
    static_configs:
      - targets: ['worker1:9001']
  - job_name: 'worker2'
    static_configs:
      - targets: ['worker2:9002']
  - job_name: 'worker3'
    static_configs:
      - targets: ['worker3:9003']
